// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ME.Extension.NTier
{
    internal sealed partial class Vsix
    {
        public const string Id = "ME.Extension.NTier.9a4045c7-fc38-4d40-96a6-e928435dd46c";
        public const string Name = "ME.Extension.NTier";
        public const string Description = @"This extension provides options to the context menu for creating essential components for projects working with N-Tier Architecture. The extension includes commands to automatically create Entity, Dto, Repository, and ServiceHelper items directly from the context menu by selecting ""Create Dto"", ""Create Repository"" or ""Create Service.""";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "BugraME";
        public const string Tags = "Extension, NTier, Architecture, Dto, Repository, Service";
    }
}
