// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ME.Extension.NTier
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string ME_Extension_NTierString = "5bd181d4-cece-425d-baf4-1390061edf9a";
        public static Guid ME_Extension_NTier = new Guid(ME_Extension_NTierString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int CreateDto = 0x0100;
        public const int CreateRepository = 0x0101;
        public const int CreateService = 0x0110;
    }
}